### ISSUE TITLE
Align Left Right issue

### ISSUE THREAD

**Issue by ofaucorp** [renancsoares/react-native-datecs-printer#2]
How i can perform a left right in same line? e.g 'Hello                   world'

**Comment by recs182** [comment]
I just went through some code that was made for the printer. We used spaces for alignment, I know that it's a little messy but that was the only way to align Left and Right...

I will use `&nbsp;` bellow to represent the spaces but in our code we used **PHP's function str_pad**...

`{left} text &nbsp; &nbsp; &nbsp; &nbsp; othertext`
