### ISSUE TITLE
Erro: read failed, socket might closed or timeout, read ret: -1

### ISSUE THREAD

**Issue by AmnaHijjawi** [renancsoares/react-native-datecs-printer#4]
when i try to call  connect function it's return ...
`Erro: read failed, socket might closed or timeout, read ret: -1`
how to resolve this ?

**Comment by recs182** [comment]
Dou you have an example of your code?

**Comment by AmnaHijjawi** [comment]
I've tried your example code.. And I can print test text...
But how I can print image or Arabic text?
#For Arabic text I tried to set charset to utf-8 but it printed strange symbols

**Comment by recs182** [comment]
A function to print images is not implemented, I don't have a printer anymore so it would be impossible to me to test new code but if you have a printer and are willing to help, fell free to fork it and make the necessary changes to your use cases.

About the charset problem, I saw that some printers have configurations in itself about the charset but as I said it's impossible to me to test.

I'm sorry that I can't help any further.
